version: "3.9"

services:
web:
  build:
    context: ./frontend/frontend
    dockerfile: Dockerfile
  container_name: frontend_agendamentos
  ports:
    - "4000:4000"
  depends_on:
    - api

  api:
    build:
      context: ./backend
    container_name: api_agendamentos
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: agendamentos
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql

volumes:
  postgres_data:
